cuboSemantico= {
	('int', '+', 'int') : 'int',
	('int', '-', 'int') : 'int',
	('int', '*', 'int') : 'int',
	('int', '=', 'int') : 'int',
	
	('int', '/', 'int') : 'float',
	('float', '+', 'float') : 'float',
	('float', '-', 'float') : 'float',
	('float', '*', 'float') : 'float',
	('float', '/', 'float') : 'float',
	('float', '=', 'float') : 'float',
	('int', '+', 'float') : 'float',
	('int', '-', 'float') : 'float',
	('int', '*', 'float') : 'float',
	('int', '/', 'float') : 'float',
	('float', '+', 'int') : 'float',
	('float', '-', 'int') : 'float',
	('float', '*', 'int') : 'float',
	('float', '/', 'int') : 'float',

	('int', '>', 'int') : 'bool',
	('int', '<', 'int') : 'bool',
	('int', '>=', 'int') : 'bool',
	('int', '<=', 'int') : 'bool',
	('int', '==', 'int') : 'bool',
	('int', '<>', 'int') : 'bool',
	('float', '>', 'float') : 'bool',
	('float', '<', 'float') : 'bool',
	('float', '>=', 'float') : 'bool',
	('float', '<=', 'float') : 'bool',
	('float', '==', 'float') : 'bool',
	('float', '<>', 'float') : 'bool',
	('int', '>', 'float') : 'bool',
	('int', '<', 'float') : 'bool',
	('int', '>=', 'float') : 'bool',
	('int', '<=', 'float') : 'bool',
	('int', '==', 'float') : 'bool',
	('int', '<>', 'float') : 'bool',
	('float', '>', 'int') : 'bool',
	('float', '<', 'int') : 'bool',
	('float', '>=', 'int') : 'bool',
	('float', '<=', 'int') : 'bool',
	('float', '==', 'int') : 'bool',
	('float', '<>', 'int') : 'bool',
}